<?xml version="1.0" encoding="utf-8"?><Database Name="Bd_Exp_Transportes" Class="Bd_Exp_TransportesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=xmalmorthen.dyndns.org;Initial Catalog=Bd_Exp_Transportes;Persist Security Info=True;User ID=digitaldocs" SettingsObjectName="thumbnail.Properties.Settings" SettingsPropertyName="Bd_Exp_TransportesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ca_acciones" Member="ca_acciones">
    <Type Name="ca_acciones">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ca_acciones_de_acciones_modulo" Member="de_acciones_modulo" ThisKey="id" OtherKey="id_acccion" Type="de_acciones_modulo" />
      <Association Name="ca_acciones_hco_cambios" Member="hco_cambios" ThisKey="id" OtherKey="id_accion" Type="hco_cambios" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_configuraciones" Member="tbl_configuraciones">
    <Type Name="tbl_configuraciones">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Valor" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ca_campostrazables" Member="ca_campostrazables">
    <Type Name="ca_campostrazables">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Tamanio_Caracteres" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mascara" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="ca_campostrazables_re_expedientes_campostrazables" Member="re_expedientes_campostrazables" ThisKey="id" OtherKey="id_campotrazable" Type="re_expedientes_campostrazables" />
    </Type>
  </Table>
  <Table Name="dbo.ca_clasificaciondocumentos" Member="ca_clasificaciondocumentos">
    <Type Name="ca_clasificaciondocumentos">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="ca_clasificaciondocumentos_re_clasificaciondocumentos_documentos" Member="re_clasificaciondocumentos_documentos" ThisKey="id" OtherKey="id_clasificaciondocumento" Type="re_clasificaciondocumentos_documentos" />
      <Association Name="ca_clasificaciondocumentos_re_tramites_clasificaciondocumentos" Member="re_tramites_clasificaciondocumentos" ThisKey="id" OtherKey="id_clasificaciondocumento" Type="re_tramites_clasificaciondocumentos" />
    </Type>
  </Table>
  <Table Name="dbo.ca_clasificaciontramites" Member="ca_clasificaciontramites">
    <Type Name="ca_clasificaciontramites">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="ca_clasificaciontramites_ca_tramites" Member="ca_tramites" ThisKey="id" OtherKey="id_ClasificacionTramite" Type="ca_tramites" />
    </Type>
  </Table>
  <Table Name="dbo.ca_documentos" Member="ca_documentos">
    <Type Name="ca_documentos">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="id_Formato" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="No_Hojas" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="No_Caras" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Resguardo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Tiempo_Resguardo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Trazabilidad" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Tamanio_Caracteres_Trazables" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Mascara_Trazable" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Politica" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="ca_documentos_re_clasificaciondocumentos_documentos" Member="re_clasificaciondocumentos_documentos" ThisKey="id" OtherKey="id_documento" Type="re_clasificaciondocumentos_documentos" />
      <Association Name="ca_formatos_ca_documentos" Member="ca_formatos" ThisKey="id_Formato" OtherKey="id" Type="ca_formatos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ca_estatus" Member="ca_estatus">
    <Type Name="ca_estatus">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ca_estatus_ca_tramites" Member="ca_tramites" ThisKey="id" OtherKey="id_estatus" Type="ca_tramites" />
      <Association Name="ca_estatus_re_clasificaciondocumentos_documentos" Member="re_clasificaciondocumentos_documentos" ThisKey="id" OtherKey="id_estatus" Type="re_clasificaciondocumentos_documentos" />
      <Association Name="ca_estatus_re_expedientes_campostrazables" Member="re_expedientes_campostrazables" ThisKey="id" OtherKey="id_estatus" Type="re_expedientes_campostrazables" />
      <Association Name="ca_estatus_ma_digital" Member="ma_digital" ThisKey="id" OtherKey="id_estatus" Type="ma_digital" />
      <Association Name="ca_estatus_de_digital_campostrazables" Member="de_digital_campostrazables" ThisKey="id" OtherKey="id_estatus" Type="de_digital_campostrazables" />
      <Association Name="ca_estatus_de_digital" Member="de_digital" ThisKey="id" OtherKey="id_estatus" Type="de_digital" />
    </Type>
  </Table>
  <Table Name="dbo.ca_expedientes" Member="ca_expedientes">
    <Type Name="ca_expedientes">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="ca_expedientes_re_expedientes_campostrazables" Member="re_expedientes_campostrazables" ThisKey="id" OtherKey="id_expediente" Type="re_expedientes_campostrazables" />
      <Association Name="ca_expedientes_re_expedientes_tramites" Member="re_expedientes_tramites" ThisKey="id" OtherKey="id_expediente" Type="re_expedientes_tramites" />
    </Type>
  </Table>
  <Table Name="dbo.ca_formatos" Member="ca_formatos">
    <Type Name="ca_formatos">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ca_formatos_ca_documentos" Member="ca_documentos" ThisKey="id" OtherKey="id_Formato" Type="ca_documentos" />
    </Type>
  </Table>
  <Table Name="dbo.ca_modulos" Member="ca_modulos">
    <Type Name="ca_modulos">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Modulo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_menu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_submenu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ca_modulos_re_roles_modulos" Member="re_roles_modulos" ThisKey="id" OtherKey="id_modulo" Type="re_roles_modulos" />
    </Type>
  </Table>
  <Table Name="dbo.ca_origenes" Member="ca_origenes">
    <Type Name="ca_origenes">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ca_origenes_re_clasificaciondocumentos_documentos" Member="re_clasificaciondocumentos_documentos" ThisKey="id" OtherKey="id_origen" Type="re_clasificaciondocumentos_documentos" />
    </Type>
  </Table>
  <Table Name="dbo.ca_roles" Member="ca_roles">
    <Type Name="ca_roles">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ca_roles_re_roles_modulos" Member="re_roles_modulos" ThisKey="id" OtherKey="id_rol" Type="re_roles_modulos" />
      <Association Name="ca_roles_re_usuarios_roles_permisos" Member="re_usuarios_roles_permisos" ThisKey="id" OtherKey="id_rol" Type="re_usuarios_roles_permisos" />
    </Type>
  </Table>
  <Table Name="dbo.ca_tablas" Member="ca_tablas">
    <Type Name="ca_tablas">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="ca_tablas_hco_cambios" Member="hco_cambios" ThisKey="id" OtherKey="id_tabla" Type="hco_cambios" />
    </Type>
  </Table>
  <Table Name="dbo.ca_tiposbloqueos" Member="ca_tiposbloqueos">
    <Type Name="ca_tiposbloqueos">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="ca_tiposbloqueos_re_expedientestramites_tiposbloqueos" Member="re_expedientestramites_tiposbloqueos" ThisKey="id" OtherKey="id_tipobloqueo" Type="re_expedientestramites_tiposbloqueos" />
    </Type>
  </Table>
  <Table Name="dbo.ca_tramites" Member="ca_tramites">
    <Type Name="ca_tramites">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Descripcion_Breve" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Alcance_Inicial" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Alcance_Final" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="id_ClasificacionTramite" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ca_tramites_re_expedientes_tramites" Member="re_expedientes_tramites" ThisKey="id" OtherKey="id_tramite" Type="re_expedientes_tramites" />
      <Association Name="ca_tramites_re_tramites_clasificaciondocumentos" Member="re_tramites_clasificaciondocumentos" ThisKey="id" OtherKey="id_tramie" Type="re_tramites_clasificaciondocumentos" />
      <Association Name="ca_clasificaciontramites_ca_tramites" Member="ca_clasificaciontramites" ThisKey="id_ClasificacionTramite" OtherKey="id" Type="ca_clasificaciontramites" IsForeignKey="true" />
      <Association Name="ca_estatus_ca_tramites" Member="ca_estatus" ThisKey="id_estatus" OtherKey="id" Type="ca_estatus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ca_usuarios" Member="ca_usuarios">
    <Type Name="ca_usuarios">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usuario" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="contrasenia" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CURP" Type="System.String" DbType="VarChar(18)" CanBeNull="true" />
      <Column Name="Nombres" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Apellido1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Apellido2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="ca_usuarios_hco_cambios" Member="hco_cambios" ThisKey="id" OtherKey="id_usuario" Type="hco_cambios" />
      <Association Name="ca_usuarios_re_usuarios_roles_permisos" Member="re_usuarios_roles_permisos" ThisKey="id" OtherKey="id_usuario" Type="re_usuarios_roles_permisos" />
    </Type>
  </Table>
  <Table Name="dbo.de_acciones_modulo" Member="de_acciones_modulo">
    <Type Name="de_acciones_modulo">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_re_roles_modulos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_acccion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ca_acciones_de_acciones_modulo" Member="ca_acciones" ThisKey="id_acccion" OtherKey="id" Type="ca_acciones" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.hco_cambios" Member="hco_cambios">
    <Type Name="hco_cambios">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_tabla" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="id_accion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="valores" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="ca_acciones_hco_cambios" Member="ca_acciones" ThisKey="id_accion" OtherKey="id" Type="ca_acciones" IsForeignKey="true" />
      <Association Name="ca_tablas_hco_cambios" Member="ca_tablas" ThisKey="id_tabla" OtherKey="id" Type="ca_tablas" IsForeignKey="true" />
      <Association Name="ca_usuarios_hco_cambios" Member="ca_usuarios" ThisKey="id_usuario" OtherKey="id" Type="ca_usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.re_clasificaciondocumentos_documentos" Member="re_clasificaciondocumentos_documentos">
    <Type Name="re_clasificaciondocumentos_documentos">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_clasificaciondocumento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_documento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_origen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="orden" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="obligatorio" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="re_clasificaciondocumentos_documentos_de_digital" Member="de_digital" ThisKey="id" OtherKey="id_re_clasificaciondocumento_documento" Type="de_digital" />
      <Association Name="ca_clasificaciondocumentos_re_clasificaciondocumentos_documentos" Member="ca_clasificaciondocumentos" ThisKey="id_clasificaciondocumento" OtherKey="id" Type="ca_clasificaciondocumentos" IsForeignKey="true" />
      <Association Name="ca_documentos_re_clasificaciondocumentos_documentos" Member="ca_documentos" ThisKey="id_documento" OtherKey="id" Type="ca_documentos" IsForeignKey="true" />
      <Association Name="ca_estatus_re_clasificaciondocumentos_documentos" Member="ca_estatus" ThisKey="id_estatus" OtherKey="id" Type="ca_estatus" IsForeignKey="true" />
      <Association Name="ca_origenes_re_clasificaciondocumentos_documentos" Member="ca_origenes" ThisKey="id_origen" OtherKey="id" Type="ca_origenes" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.re_expedientes_campostrazables" Member="re_expedientes_campostrazables">
    <Type Name="re_expedientes_campostrazables">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_expediente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_campotrazable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="es_principal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="id_estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="re_expedientes_campostrazables_de_digital_campostrazables" Member="de_digital_campostrazables" ThisKey="id" OtherKey="id_re_expediente_campotrazable" Type="de_digital_campostrazables" />
      <Association Name="ca_campostrazables_re_expedientes_campostrazables" Member="ca_campostrazables" ThisKey="id_campotrazable" OtherKey="id" Type="ca_campostrazables" IsForeignKey="true" />
      <Association Name="ca_estatus_re_expedientes_campostrazables" Member="ca_estatus" ThisKey="id_estatus" OtherKey="id" Type="ca_estatus" IsForeignKey="true" />
      <Association Name="ca_expedientes_re_expedientes_campostrazables" Member="ca_expedientes" ThisKey="id_expediente" OtherKey="id" Type="ca_expedientes" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.re_expedientes_tramites" Member="re_expedientes_tramites">
    <Type Name="re_expedientes_tramites">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_expediente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_tramite" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="re_expedientes_tramites_re_expedientestramites_tiposbloqueos" Member="re_expedientestramites_tiposbloqueos" ThisKey="id" OtherKey="id_re_expediente_tramite" Type="re_expedientestramites_tiposbloqueos" />
      <Association Name="re_expedientes_tramites_ma_digital" Member="ma_digital" ThisKey="id" OtherKey="id_re_expediente_tramite" Type="ma_digital" />
      <Association Name="ca_expedientes_re_expedientes_tramites" Member="ca_expedientes" ThisKey="id_expediente" OtherKey="id" Type="ca_expedientes" IsForeignKey="true" />
      <Association Name="ca_tramites_re_expedientes_tramites" Member="ca_tramites" ThisKey="id_tramite" OtherKey="id" Type="ca_tramites" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.re_expedientestramites_tiposbloqueos" Member="re_expedientestramites_tiposbloqueos">
    <Type Name="re_expedientestramites_tiposbloqueos">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_re_expediente_tramite" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_tipobloqueo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="no_horas" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="no_dias" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="ca_tiposbloqueos_re_expedientestramites_tiposbloqueos" Member="ca_tiposbloqueos" ThisKey="id_tipobloqueo" OtherKey="id" Type="ca_tiposbloqueos" IsForeignKey="true" />
      <Association Name="re_expedientes_tramites_re_expedientestramites_tiposbloqueos" Member="re_expedientes_tramites" ThisKey="id_re_expediente_tramite" OtherKey="id" Type="re_expedientes_tramites" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.re_roles_modulos" Member="re_roles_modulos">
    <Type Name="re_roles_modulos">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_rol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_modulo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ca_modulos_re_roles_modulos" Member="ca_modulos" ThisKey="id_modulo" OtherKey="id" Type="ca_modulos" IsForeignKey="true" />
      <Association Name="ca_roles_re_roles_modulos" Member="ca_roles" ThisKey="id_rol" OtherKey="id" Type="ca_roles" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.re_tramites_clasificaciondocumentos" Member="re_tramites_clasificaciondocumentos">
    <Type Name="re_tramites_clasificaciondocumentos">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_tramie" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_clasificaciondocumento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ca_clasificaciondocumentos_re_tramites_clasificaciondocumentos" Member="ca_clasificaciondocumentos" ThisKey="id_clasificaciondocumento" OtherKey="id" Type="ca_clasificaciondocumentos" IsForeignKey="true" />
      <Association Name="ca_tramites_re_tramites_clasificaciondocumentos" Member="ca_tramites" ThisKey="id_tramie" OtherKey="id" Type="ca_tramites" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.re_usuarios_roles_permisos" Member="re_usuarios_roles_permisos">
    <Type Name="re_usuarios_roles_permisos">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_rol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ca_roles_re_usuarios_roles_permisos" Member="ca_roles" ThisKey="id_rol" OtherKey="id" Type="ca_roles" IsForeignKey="true" />
      <Association Name="ca_usuarios_re_usuarios_roles_permisos" Member="ca_usuarios" ThisKey="id_usuario" OtherKey="id" Type="ca_usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ma_digital" Member="ma_digital">
    <Type Name="ma_digital">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_re_expediente_tramite" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha_hora_creacion" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nota" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="fecha_hora_bloqueo" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="id_estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ma_digital_de_digital_campostrazables" Member="de_digital_campostrazables" ThisKey="id" OtherKey="id_ma_digital" Type="de_digital_campostrazables" />
      <Association Name="ma_digital_de_digital" Member="de_digital" ThisKey="id" OtherKey="id_ma_digital" Type="de_digital" />
      <Association Name="ca_estatus_ma_digital" Member="ca_estatus" ThisKey="id_estatus" OtherKey="id" Type="ca_estatus" IsForeignKey="true" />
      <Association Name="re_expedientes_tramites_ma_digital" Member="re_expedientes_tramites" ThisKey="id_re_expediente_tramite" OtherKey="id" Type="re_expedientes_tramites" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.de_digital_campostrazables" Member="de_digital_campostrazables">
    <Type Name="de_digital_campostrazables">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_ma_digital" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_re_expediente_campotrazable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="valor_trazable" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_hora_creacion" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_estatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ca_estatus_de_digital_campostrazables" Member="ca_estatus" ThisKey="id_estatus" OtherKey="id" Type="ca_estatus" IsForeignKey="true" />
      <Association Name="ma_digital_de_digital_campostrazables" Member="ma_digital" ThisKey="id_ma_digital" OtherKey="id" Type="ma_digital" IsForeignKey="true" />
      <Association Name="re_expedientes_campostrazables_de_digital_campostrazables" Member="re_expedientes_campostrazables" ThisKey="id_re_expediente_campotrazable" OtherKey="id" Type="re_expedientes_campostrazables" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.de_digital" Member="de_digital">
    <Type Name="de_digital">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_ma_digital" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="thumbnail" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="id_re_clasificaciondocumento_documento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="imagen" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="fecha_hora_creacion" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="valor_trazable" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="id_estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ca_estatus_de_digital" Member="ca_estatus" ThisKey="id_estatus" OtherKey="id" Type="ca_estatus" IsForeignKey="true" />
      <Association Name="ma_digital_de_digital" Member="ma_digital" ThisKey="id_ma_digital" OtherKey="id" Type="ma_digital" IsForeignKey="true" />
      <Association Name="re_clasificaciondocumentos_documentos_de_digital" Member="re_clasificaciondocumentos_documentos" ThisKey="id_re_clasificaciondocumento_documento" OtherKey="id" Type="re_clasificaciondocumentos_documentos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_ListaTramitesActivos" Member="vw_ListaTramitesActivos">
    <Type Name="vw_ListaTramitesActivos">
      <Column Name="id_expediente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion_Expediente" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="id_clasificaciontramite" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion_clasificaciontramite" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="id_tramite" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre_tramite" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion_tramite" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Descripcion_Breve_tramite" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Alcance_Inicial_tramite" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Alcance_Final_tramite" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="id_estatus_tramite" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion_estatus_tramite" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_re_expedientes_tramites" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_tipobloqueo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="descripcion_bloqueo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="no_horas_bloqueo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="no_dias_bloqueo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.pa_CampostrazablesActivosporExpediente" Method="pa_CampostrazablesActivosporExpediente">
    <Parameter Name="id_expediente" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_CampostrazablesActivosporExpedienteResult">
      <Column Name="id_re_expedientes_campostrazables" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_campotrazable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Tamanio_Caracteres" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mascara" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="es_principal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_Permsos_Modulos" Method="pa_Permsos_Modulos">
    <Parameter Name="id_usuario" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_Permsos_ModulosResult">
      <Column Name="id_modulo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_menu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_submenu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Modulo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_CampostrazablesNoEnlazadosporExpediente" Method="pa_CampostrazablesNoEnlazadosporExpediente">
    <Parameter Name="id_expediente" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_CampostrazablesNoEnlazadosporExpedienteResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TAMANIO_CARACTERES" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MASCARA" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_CampostrazablesporExpediente" Method="pa_CampostrazablesporExpediente">
    <Parameter Name="id_expediente" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_CampostrazablesporExpedienteResult">
      <Column Name="id_re_expedientes_campostrazables" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_campotrazable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Tamanio_Caracteres" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mascara" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="es_principal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="estatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_DocumentosNoEnlazadosporClasificacionDocumento" Method="pa_DocumentosNoEnlazadosporClasificacionDocumento">
    <Parameter Name="id_clasificacion" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_DocumentosNoEnlazadosporClasificacionDocumentoResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ID_FORMATO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FORMATO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NO_HOJAS" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="NO_CARAS" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ESTADO" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPCIONESTADO" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="RESGUARDO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TIEMPO_RESGUARDO" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TRAZABILIDAD" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TAMANIO_CARACTERES_TRAZABLES" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MASCARA_TRAZABLE" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="POLITICA" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_obtener_fecha" Method="pa_obtener_fecha">
    <ElementType Name="pa_obtener_fechaResult">
      <Column Name="Fecha" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_obtener_hora" Method="pa_obtener_hora">
    <ElementType Name="pa_obtener_horaResult">
      <Column Name="Hora" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_DocumentosporClasificacionDocumento" Method="pa_DocumentosporClasificacionDocumento">
    <Parameter Name="id_clasificaciondocumento" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_DocumentosporClasificacionDocumentoResult">
      <Column Name="id_re_clasificaciondocumento_documento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_documento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="id_Formato" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DescripcionFormato" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="No_Hojas" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="No_Caras" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPCIONESTADO" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="Resguardo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Tiempo_Resguardo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Trazabilidad" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Tamanio_Caracteres_Trazables" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Mascara_Trazable" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Politica" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="id_estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_origen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="origen" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="orden" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="obligatorio" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_ordenaporordenmayor" Method="pa_ordenaporordenmayor">
    <Parameter Name="ID_CLASIFICACIONDOCUMENTO" Parameter="iD_CLASIFICACIONDOCUMENTO" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_ORIGEN" Parameter="iD_ORIGEN" Type="System.Int32" DbType="Int" />
    <Parameter Name="ORDENDEPARTIDA" Parameter="oRDENDEPARTIDA" Type="System.Int32" DbType="Int" />
    <Parameter Name="ORDENDEFIN" Parameter="oRDENDEFIN" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.pa_ordenaporordenmenor" Method="pa_ordenaporordenmenor">
    <Parameter Name="ID_CLASIFICACIONDOCUMENTO" Parameter="iD_CLASIFICACIONDOCUMENTO" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_ORIGEN" Parameter="iD_ORIGEN" Type="System.Int32" DbType="Int" />
    <Parameter Name="ORDENDEPARTIDA" Parameter="oRDENDEPARTIDA" Type="System.Int32" DbType="Int" />
    <Parameter Name="ORDENDEFIN" Parameter="oRDENDEFIN" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.pa_ClasificacionDocumentosporTramite" Method="pa_ClasificacionDocumentosporTramite">
    <Parameter Name="id_tramite" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_ClasificacionDocumentosporTramiteResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_clasificaciondocumento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_ClasificacionDocumentosNoEnlazadosporTramite" Method="pa_ClasificacionDocumentosNoEnlazadosporTramite">
    <Parameter Name="id_tramite" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_ClasificacionDocumentosNoEnlazadosporTramiteResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_RolesporIdUsuario" Method="pa_RolesporIdUsuario">
    <Parameter Name="id_usuario" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_RolesporIdUsuarioResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ENLAZADO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_ModulosporIdRol" Method="pa_ModulosporIdRol">
    <Parameter Name="id_rol" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_ModulosporIdRolResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MODULO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_MENU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_SUBMENU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ENLAZADO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_ObtenerDocumentosporTramiteyOrigen" Method="pa_ObtenerDocumentosporTramiteyOrigen">
    <Parameter Name="id_tramite" Type="System.Int32" DbType="Int" />
    <Parameter Name="id_origen" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_ObtenerDocumentosporTramiteyOrigenResult">
      <Column Name="id_re_clasificaciondocumentos_documentos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_clasificaciondocumento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion_clasificaciondocumento" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="id_documento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Trazabilidad" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="obligatorio" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="orden" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Tamanio_Caracteres_Trazables" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Mascara_Trazable" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_obtener_fechahora" Method="pa_obtener_fechahora">
    <ElementType Name="pa_obtener_fechahoraResult">
      <Column Name="FechaHora" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_ReferenciaExpedientesporValorTrazable" Method="pa_ReferenciaExpedientesporValorTrazable">
    <Parameter Name="valor_trazable" Type="System.String" DbType="VarChar(200)" />
    <ElementType Name="pa_ReferenciaExpedientesporValorTrazableResult">
      <Column Name="id_ma_digital" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_estatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fecha_hora_creacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="nota" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="tramite" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="expediente" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_CampostrazablesRegistradosporId_ma_digital" Method="pa_CampostrazablesRegistradosporId_ma_digital">
    <Parameter Name="id_ma_digital" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_CampostrazablesRegistradosporId_ma_digitalResult">
      <Column Name="id_re_expediente_campotrazable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_campotrazable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Tamanio_Caracteres" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mascara" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="es_principal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="valor_trazable" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_RegistrosDigitalesRegistradosporId_ma_digital" Method="pa_RegistrosDigitalesRegistradosporId_ma_digital">
    <Parameter Name="id_ma_digital" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_RegistrosDigitalesRegistradosporId_ma_digitalResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="thumbnail" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" />
      <Column Name="id_re_clasificaciondocumento_documento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha_hora_creacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="valor_trazable" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="clasificaciondocumento" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Documento" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="id_origen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Origen" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_ordenaporborrado" Method="pa_ordenaporborrado">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.pa_ordenaporcambiodeorigen" Method="pa_ordenaporcambiodeorigen">
    <Parameter Name="ID_CLASIFICACIONDOCUMENTO" Parameter="iD_CLASIFICACIONDOCUMENTO" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_ORIGEN" Parameter="iD_ORIGEN" Type="System.Int32" DbType="Int" />
    <Parameter Name="ORDENDEPARTIDA" Parameter="oRDENDEPARTIDA" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_NUEVOORIGEN" Parameter="iD_NUEVOORIGEN" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>