<?xml version="1.0" encoding="utf-8"?><Database Name="Bd_Expedientes_Web" Class="Bd_Expedientes_WebDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=xmalmorthen.dyndns.org;Initial Catalog=Bd_Expedientes_Web;Persist Security Info=True;User ID=digitaldocs" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Bd_Expedientes_WebConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ca_nodos" Member="ca_nodos">
    <Type Name="ca_nodos">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nodo" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="url_servicio_rest" Type="System.String" DbType="VarChar(8000) NOT NULL" CanBeNull="false" />
      <Column Name="usuario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="contrasenia" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fecha_registro" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="ca_nodos_re_nodos_usuarios" Member="re_nodos_usuarios" ThisKey="id" OtherKey="id_nodo" Type="re_nodos_usuarios" />
    </Type>
  </Table>
  <Table Name="dbo.re_nodos_usuarios" Member="re_nodos_usuarios">
    <Type Name="re_nodos_usuarios">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_nodo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="f_registro" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="ca_nodos_re_nodos_usuarios" Member="ca_nodos" ThisKey="id_nodo" OtherKey="id" Type="ca_nodos" IsForeignKey="true" />
      <Association Name="ca_usuarios_re_nodos_usuarios" Member="ca_usuarios" ThisKey="id_usuario" OtherKey="id" Type="ca_usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ca_usuarios" Member="ca_usuarios">
    <Type Name="ca_usuarios">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usuario" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="contrasenia" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="curp" Type="System.String" DbType="VarChar(18)" CanBeNull="true" />
      <Column Name="nombres" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apellido1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apellido2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cargo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="f_registro" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="es_administrador" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="tocken" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="ca_usuarios_re_nodos_usuarios" Member="re_nodos_usuarios" ThisKey="id" OtherKey="id_usuario" Type="re_nodos_usuarios" />
    </Type>
  </Table>
  <Function Name="dbo.pa_obtener_nodos" Method="pa_obtener_nodos">
    <Parameter Name="id_usuario" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_obtener_nodosResult">
      <Column Name="activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nodo" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="url_servicio_rest" Type="System.String" DbType="VarChar(8000) NOT NULL" CanBeNull="false" />
      <Column Name="usuario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="contrasenia" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_obtener_nodo" Method="pa_obtener_nodo">
    <Parameter Name="id_usuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="id_nodo" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_obtener_nodoResult">
      <Column Name="activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nodo" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="url_servicio_rest" Type="System.String" DbType="VarChar(8000) NOT NULL" CanBeNull="false" />
      <Column Name="usuario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="contrasenia" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_obtener_nodos_no_enlazados" Method="pa_obtener_nodos_no_enlazados">
    <Parameter Name="id_usuario" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_obtener_nodos_no_enlazadosResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nodo" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="url_servicio_rest" Type="System.String" DbType="VarChar(8000) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_Fecha" Method="pa_Fecha">
    <ElementType Name="pa_FechaResult">
      <Column Name="Fecha" Type="System.String" DbType="NVarChar(44)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_Hora" Method="pa_Hora">
    <ElementType Name="pa_HoraResult">
      <Column Name="Hora" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>